# Generated by Django 3.2.13 on 2022-10-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comment_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user_name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_name',
            new_name='user',
        ),
    ]
