SELECT (
    CASE
        WHEN PRICE < 10000 THEN 0
        ELSE TRUNCATE (PRICE, -4)
        END) AS PRICE_GROUP, COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP 

-- PRICE가 0보다 클 경우 PRICE를 뒤에서 4자리를 뺀다.
-- 그러면 뺀 네자리를 0으로 입력되어 나온다.