-- PERCEN_RANK() 함수 사용
-- 순위를 낸 임시 테이블 사용

WITH RANKED AS (
    SELECT ID, PERCEN_RANK() OVER (
        ORDER BY SIZE_OF_COLOBY DESC
    ) AS PR 
    FROM ECOLI_DATA
)

SELECT ID,
    CASE WHEN PR <= 0.25 THEN 'CRITICAL'
    WHEN PR <= 0.50 THEN 'HIGH'
    WHEN PR <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW' END AS COLONY_NAME 
FROM RANKED 
ORDER BY ID 