-- 월별 자동차 ID 별 총 대여 횟수가 5회 이상인 자동차를 탐색하기 위해 서브쿼리 JOIN 사용

SELECT DATE_FORMAT(H.START_DATE, '%m') AS MONTH,
    H.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
    JOIN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
    ) C 
    ON H.CAR_ID = C.CAR_ID
WHERE H.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, H.CAR_ID
ORDER BY MONTH, H.CAR_ID DESC