SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H INNER JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID
WHERE CAR_TYPE = '세단' AND DATE_FORMAT(START_DATE, '%Y-%m') = '2022-10'
ORDER BY H.CAR_ID DESC