-- 서브쿼리 조인 사용

SELECT I.ID AS ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I JOIN FISH_NAME_INFO N 
    ON I.FISH_TYPE = N.FISH_TYPE
    JOIN (
        SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
        FROM FISH_INFO 
        GROUP BY FISH_TYPE
    ) M ON I.FISH_TYPE = M.FISH_TYPE AND I.LENGTH = M.MAX_LENGTH 
ORDER BY I.ID 