-- 포인트
-- GROUP BY로 식당ID를 묶어야 식당별 리뷰 점수가 산정됨

SELECT R.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW R LEFT JOIN REST_INFO I
     ON R.REST_ID = I.REST_ID
GROUP BY R.REST_ID
HAVING ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC