SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국', '김치', '식용유')
    GROUP BY CATEGORY
    )
ORDER BY MAX_PRICE DESC

-- 서브쿼리로 카테고리별 가장 높은 가격 출력

-- 서브쿼리 조인 사용
SELECT P.CATEGORY, P.PRICE AS MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT P 
    JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
        FROM FOOD_PRODUCT
        GROUP BY CATEGORY
        ) M ON P.PRICE = M.MAX_PRICE 
WHERE P.CATEGORY = '과자' OR P.CATEGORY = '국' OR P.CATEGORY = '김치' OR P.CATEGORY = '식용유'
GROUP BY P.CATEGORY
ORDER BY MAX_PRICE DESC