SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국', '김치', '식용유')
    GROUP BY CATEGORY
    )
ORDER BY MAX_PRICE DESC

-- 서브쿼리로 카테고리별 가장 높은 가격 출력