-- 기존의 테이블을 서브쿼리로 정리 후 JOIN

SELECT H.FLAVOR
FROM FIRST_HALF H JOIN (
    SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) J ON H.FLAVOR = J.FLAVOR
GROUP BY H.FLAVOR
ORDER BY (H.TOTAL_ORDER + J.TOTAL_ORDER) DESC 
LIMIT 3