-- LEFT JOIN을 통해 조회된 NULL값 사용

SELECT C.CAR_ID, C.CAR_TYPE,
    ROUND(30 * C.DAILY_FEE *
            (1 - (SELECT DISCOUNT_RATE
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
                WHERE P.CAR_TYPE = C.CAR_TYPE
                    AND DURATION_TYPE LIKE '30일%') / 100)
        , 0) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR C LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
    ON C.CAR_ID = H.CAR_ID 
    AND (H.END_DATE >= '2022-11-01' AND H.START_DATE <= '2022-11-30')
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND H.CAR_ID IS NULL -- 해당 기간에 대여 중인 자동차가 없어야 하므로
    AND (30 * C.DAILY_FEE) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC 
