# Generated by Django 3.2.13 on 2022-10-17 20:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221017_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
